### ISSUE TITLE
design header

### ISSUE THREAD

**Issue by anoukbruinn** [WesleySchorel/the-startup-responsive-interactieve-website#2]
Ik zelf zou het hamburgermenu rechts doen, in plaats van account rechts en menu links. Zelf vind ik dat mooier.

**Comment by DorienD** [comment]
@anoukbruinn kan je iets specifieker zijn wat je er mooier aan vindt?

**Comment by anoukbruinn** [comment]
Bij het uitklappen zou dan bijvoorbeeld Het hoofdje naar links kunnen verschuiven
